prevent throwing an error when token not found for position
invariant-labs/webapp-a0 pull request #179
Opened 2024-07-09 11:23 UTC by p6te

2024-07-09 15:46 UTC, zielvna commented on src/store/selectors/positions.ts
> +        console.log('Token not found for position: ', stringifyWithBigInt(position))
i'm not sure if we should create function just to print something in console one time, you can print address of the missing token

2024-07-10 07:28 UTC, zielvna approved these changes

2024-07-10 12:41 UTC, wojciech-cichocki requested changes
Check this case:
[Screencast from 10.07.2024 14:39:45.webm](https://github.com/invariant-labs/webapp-a0/assets/43304803/5e80d9f1-ecda-48c8-accf-ebd94bfbfb0b)

2024-07-10 12:46 UTC, p6te commented
> Check this case: [Screencast from 10.07.2024 14:39:45.webm](https://github.com/invariant-labs/webapp-a0/assets/43304803/5e80d9f1-ecda-48c8-accf-ebd94bfbfb0b)

this is another bug, which I'm working on. But not in this pr.

2024-07-11 05:04 UTC, wojciech-cichocki approved these changes

2024-07-11 05:05 UTC, merged