add wallet reconnected snackbar
invariant-labs/webapp-a0 pull request #198
Opened 2024-07-15 10:25 UTC by zielvna

2024-07-15 11:51 UTC, p6te commented on src/store/sagas/wallet.ts
> +          variant: 'info',
for wallet connect probably better looks like 'success' variant

2024-07-16 06:22 UTC, p6te reviewed
There is still missing functionality for this task. 
We want to show the snackbar with reconnect button when user change the account in wallet extension. 
1. connect the wallet.
2. change account in wallet extension
![image](https://github.com/user-attachments/assets/5dba06df-e860-4bec-974b-0940644a743e)
3. Show snackbar - wallet reconnected, with button to reconnect wallet on invariant

2024-07-17 06:29 UTC, p6te commented on src/containers/HeaderWrapper/HeaderWrapper.tsx
> +            dispatch(walletActions.connect(true))
apply these changes to all 'connect wallet' buttons in the app

2024-07-17 14:07 UTC, p6te approved these changes

2024-07-18 09:28 UTC, wojciech-cichocki requested changes
I don't know if this error occurred with this PR or if it exists on dev, but there is a problem with 'change wallet'. Below is a video:
[Screencast from 18.07.2024 11:21:43.webm](https://github.com/user-attachments/assets/6967f3f0-8209-4df1-a70c-ea73292eb329)

2024-07-19 06:58 UTC, p6te commented
after refreshing the page wallet is not reconnected.
[Nagranie ekranu z 19.07.2024 08:56:14.webm](https://github.com/user-attachments/assets/ccb01bed-867a-4248-b472-d006a96d3363)

2024-07-19 13:33 UTC, p6te commented
> after refreshing the page wallet is not reconnected. [Nagranie ekranu z 19.07.2024 08:56:14.webm](https://github.com/user-attachments/assets/ccb01bed-867a-4248-b472-d006a96d3363)

it works correctly on localhost

2024-07-19 13:33 UTC, p6te approved these changes

2024-07-20 23:31 UTC, wojciech-cichocki requested changes
In my case it doesn't work

2024-07-23 11:41 UTC, wojciech-cichocki approved these changes

2024-07-23 11:42 UTC, merged