replace nightly selector with new selector
invariant-labs/webapp-a0 pull request #200
Opened 2024-07-15 15:47 UTC by zielvna

2024-07-16 11:10 UTC, p6te reviewed
I still see nightly selector 
![image](https://github.com/user-attachments/assets/32b2bf15-f7ce-4e1f-9f80-e0cb1adea879)
and after select nightly, the modal close, and wallet is not connected

2024-07-16 16:39 UTC, wojciech-cichocki requested changes
I have polkadot.js, but I received this error after I tried to connect the wallet via the header:
![image](https://github.com/user-attachments/assets/7a8a9b7f-d514-44f8-9309-474c6c08d792)

2024-07-19 05:56 UTC, p6te reviewed
after i chose polkadot wallet, i couldn't switch to another one. 
1. Is it intentional that after disconnect, and when clicking 'connect wallet', a wallet is automatically connected, without options to choose?
2. When I chose polkadot wallet, I tried switching to the nightly wallet. I still connect to polkadot address. 

[Nagranie ekranu z 19.07.2024 07:50:08.webm](https://github.com/user-attachments/assets/462522f0-32a0-474b-af54-ab787598f30d)

2024-07-19 14:53 UTC, p6te approved these changes

2024-07-24 10:27 UTC, closed without merging