add ui improvements
invariant-labs/webapp-a0 pull request #204
Opened 2024-07-16 09:55 UTC by p6te

1. add hover effect for refresher and exchange ratio 
![image](https://github.com/user-attachments/assets/f4d7d1c6-ab16-4f92-a6cf-b1d251884541)
2. style scrollbar for select tokens on desktop 
![image](https://github.com/user-attachments/assets/62a8d5cd-1a2a-4ca4-bdc1-b8fccae4747c)
3. add not allowed cursor
![image](https://github.com/user-attachments/assets/66058b41-4d3c-45a6-8107-42b9a4c05811)
4. highlight flags on hover 
![image](https://github.com/user-attachments/assets/ac96fb10-10e2-4d0c-a5f3-2d9f407c5226)
5. hide balances when token is not selected
![image](https://github.com/user-attachments/assets/8cbb9fcb-e574-4548-a24e-91264dc84560)

2024-07-16 11:15 UTC, zielvna commented
![image](https://github.com/user-attachments/assets/a7b0fbca-8379-49bc-90f5-92b9c8622d23)
can you also change `Select` to `-`? we talked about it and it is a little bit misleading for user

2024-07-18 08:11 UTC, zielvna approved these changes

2024-07-18 09:12 UTC, wojciech-cichocki requested changes
IMO, we should display `Balance: - [MAX]` inside the "Deposit Amount" fields instead of leaving them empty, as after choosing the tokens, other elements of the UI change location.

[Screencast from 18.07.2024 10:42:50.webm](https://github.com/user-attachments/assets/eda8e047-c136-4161-ada1-1138fba643c4)

2024-07-19 08:10 UTC, zielvna commented
![image](https://github.com/user-attachments/assets/8ca4d270-a704-41dc-a1bb-28c43d15f45e)
remove highlighting on hover from balance when token is not selected

2024-07-19 16:56 UTC, zielvna approved these changes

2024-07-20 21:39 UTC, wojciech-cichocki approved these changes

2024-07-20 21:40 UTC, merged