Add styles for snackbars
invariant-labs/webapp-a0 pull request #207
Opened 2024-07-16 14:54 UTC by p6te

![image](https://github.com/user-attachments/assets/a2b36a14-c807-4491-a26d-0ffb8c661ae6)

2024-07-17 11:22 UTC, zielvna commented
![image](https://github.com/user-attachments/assets/49c6469e-d1d7-41fc-95d1-966fc43e7adc)
is it possible to remove this tint?

2024-07-18 08:15 UTC, zielvna approved these changes

2024-07-18 12:09 UTC, wojciech-cichocki requested changes
Is the animation of the gradient expanding in the snack bar "Airdrop processing..." intentional?
[Screencast from 18.07.2024 14:07:26.webm](https://github.com/user-attachments/assets/81ec1447-372d-404d-90fb-95d0cd557369)

2024-07-20 23:29 UTC, wojciech-cichocki approved these changes

2024-07-20 23:29 UTC, merged