add labels to swap
invariant-labs/webapp-a0 pull request #209
Opened 2024-07-17 08:21 UTC by p6te

![image](https://github.com/user-attachments/assets/f7df97d4-4c12-4bae-ae26-6c73480e6b13)

2024-07-17 11:26 UTC, zielvna approved these changes

2024-07-17 13:36 UTC, wojciech-cichocki requested changes
Issues with order of tokens:
BTC price = ~1$
USDC price = ~64.69K

![image](https://github.com/user-attachments/assets/746b4b21-1b40-42e3-93ed-9e219f78bc40)

2024-07-19 09:28 UTC, zielvna commented
![image](https://github.com/user-attachments/assets/045a16e4-47de-45ef-8107-58e47d25fc1b)
can you make it more aligned with texts? either make it bigger or make gap between texts smaller

2024-07-19 16:57 UTC, zielvna approved these changes

2024-07-20 22:50 UTC, wojciech-cichocki approved these changes

2024-07-20 22:50 UTC, merged