Add y axis for stats charts
invariant-labs/webapp-a0 pull request #213
Opened 2024-07-18 09:34 UTC by p6te

![image](https://github.com/user-attachments/assets/0a0fd7c1-59f4-4255-b33d-3e4fc05cdbad)
![image](https://github.com/user-attachments/assets/61ce56b4-4abd-4280-8a5b-974529fdd54e)

2024-07-18 09:59 UTC, zielvna commented
![image](https://github.com/user-attachments/assets/042ec137-aeab-4702-bad5-ae0a5bea92c4)
height of that badge on the right should be fixed

![image](https://github.com/user-attachments/assets/d4eb676f-9711-45ca-adb0-f90a1363fd09)
also is it possible to increase distance between y axis labels and graph a little just like x axis labels are a few pixels below graph?

2024-07-18 10:58 UTC, zielvna approved these changes

2024-07-18 14:08 UTC, wojciech-cichocki requested changes
We will try icon instead of buttons

2024-07-20 23:23 UTC, wojciech-cichocki reviewed
This PR goes into the 'ON HOLD' state

2024-07-24 16:01 UTC, wojciech-cichocki approved these changes

2024-07-24 21:43 UTC, merged