update empty placeholder
invariant-labs/webapp-a0 pull request #214
Opened 2024-07-18 16:25 UTC by zielvna

2024-07-19 05:39 UTC, p6te commented on src/components/EmptyPlaceholder/EmptyPlaceholder.tsx
>  import empty from '@static/svg/empty.svg'
when you import icons, first we move them to the icons file to have them in one object 
![image](https://github.com/user-attachments/assets/904496ea-e95e-4c09-ab1c-0118245ceb06)

2024-07-19 13:20 UTC, wojciech-cichocki requested changes
The goal of this task is to ensure consistency between these two designs. In my opinion, the first one looks significantly better. To achieve a unified look, we could consider changing the background, slightly reducing the text size, and moving the button higher. It's challenging to provide precise instructions, but the key is to make both designs appear cohesive:

![Screenshot from 2024-07-19 15-15-37](https://github.com/user-attachments/assets/84980239-31bc-4b3d-b7df-b1cd91c08593)

![Screenshot from 2024-07-19 15-15-43](https://github.com/user-attachments/assets/5f5d17d8-37a1-438c-9c79-ba7475ac5177)

2024-07-19 15:54 UTC, p6te approved these changes

2024-07-20 23:00 UTC, wojciech-cichocki requested changes
IMO it's still not consistent. This text is too bold compared to the other texts, which isn't the case anywhere else. Because of this, it looks like a design taken from another app. 

Overall, this graphic isn't meant to stand out. Rhe elements should have a "blank and perform an action" vibe. I think the darker color fit better because it gave off a more transparent component vibe.

The "connect wallet" design in this position list was okay, but after adding the new one, there's an issue

2024-07-22 10:00 UTC, closed without merging