add functionality to handle path in swap page
invariant-labs/webapp-a0 pull request #219
Opened 2024-07-22 13:00 UTC by zielvna

2024-07-22 13:50 UTC, p6te commented on src/components/Swap/Swap.tsx
> +    navigate(`/swap/${tokenFromAddress || '-'}/${tokenToAddress || '-'}`, {
maybe it's better to add token names instead of addresses to URL, like we have on create position. It is more readable for user

2024-07-22 14:56 UTC, p6te commented
after click second time in the row in swap tab button, URL path is cleared from tokens 
[Nagranie ekranu z 22.07.2024 16:55:01.webm](https://github.com/user-attachments/assets/0c3e2ad8-cace-4ebb-89ad-12515af59af7)

2024-07-23 06:44 UTC, p6te approved these changes

2024-07-23 12:47 UTC, wojciech-cichocki requested changes
IMO, even if tokens are cached after reopening the app with a forced URL change, the swap tokens and URLs should always be consistent:

URL:
![Screenshot from 2024-07-23 14-20-02](https://github.com/user-attachments/assets/080829a2-1ae7-46ab-b03e-10b6b6809c2a)

SWAP PANEL:
![Screenshot from 2024-07-23 14-20-05](https://github.com/user-attachments/assets/db894cfe-3f34-45fd-82ef-fd15c798b379)

2024-07-23 14:47 UTC, wojciech-cichocki approved these changes

2024-07-23 14:48 UTC, merged