Fix position details layout and select navigation
invariant-labs/webapp-a0 pull request #238
Opened 2024-07-26 12:19 UTC by p6te

- fix highlight active path (swap) on mobile
- fix market id  and add liquidity position in position details

2024-07-26 15:21 UTC, zielvna approved these changes

2024-07-28 00:13 UTC, wojciech-cichocki requested changes
Why is this interval loader in place 1? It should be in place 2:
![image](https://github.com/user-attachments/assets/8b22ee5f-6eb9-4b70-af8d-1516faf68ec2)

2024-07-29 10:31 UTC, zielvna approved these changes

2024-07-30 08:05 UTC, wojciech-cichocki approved these changes

2024-07-30 08:09 UTC, merged