Refactor header
invariant-labs/webapp-a0 pull request #239
Opened 2024-07-26 14:51 UTC by zielvna

2024-07-26 14:54 UTC, p6te approved these changes

2024-07-28 00:20 UTC, wojciech-cichocki requested changes
Overall, I'm wondering if there's a possibility to update this header. There are a lot of buttons here; maybe we could consider merging them into one block:
![image](https://github.com/user-attachments/assets/c9c66a29-bc8a-408f-8612-0e94e4348e61)

2024-07-28 00:27 UTC, wojciech-cichocki requested changes
Isn't it possible to improve this view a bit?
![image](https://github.com/user-attachments/assets/59e93fd0-0d4c-4c59-8f05-07b1abe648c3)

2024-07-28 00:38 UTC, wojciech-cichocki approved these changes

2024-07-28 00:38 UTC, merged