Update tooltips
invariant-labs/webapp-a0 pull request #240
Opened 2024-07-26 14:52 UTC by zielvna

2024-07-26 14:54 UTC, p6te approved these changes

2024-07-27 21:41 UTC, wojciech-cichocki requested changes
Sometimes there is a problem with the tooltip on mobile devices. It would be better to extend the hover effect so that the icon cannot be selected as text - this happens quite often

https://github.com/user-attachments/assets/15e05c62-b5cb-43cc-92b7-94411db0523d

2024-07-29 16:02 UTC, p6te approved these changes

2024-07-29 20:29 UTC, wojciech-cichocki approved these changes

2024-07-29 20:30 UTC, merged