remove disable from swap inputs
invariant-labs/webapp-a0 pull request #248
Opened 2024-07-29 17:16 UTC by zielvna

2024-07-30 08:14 UTC, wojciech-cichocki commented
> Instead of the input amount, it should be the one that has the entered amount:

Instead of the input amount, it should be the one that has the selected token:

2024-07-30 13:53 UTC, p6te approved these changes

2024-07-31 03:53 UTC, wojciech-cichocki requested changes
video:
[Screencast from 31.07.2024 05:52:09.webm](https://github.com/user-attachments/assets/ef63cb45-8c5d-47a4-bdfa-16f2fbbe370f)

2024-07-31 12:55 UTC, p6te approved these changes

2024-08-02 06:10 UTC, wojciech-cichocki approved these changes

2024-08-02 06:20 UTC, wojciech-cichocki approved these changes

2024-08-02 06:20 UTC, merged