align tooltips
invariant-labs/webapp-a0 pull request #269
Opened 2024-08-06 11:46 UTC by zielvna

2024-08-06 13:30 UTC, p6te approved these changes

2024-08-06 23:06 UTC, wojciech-cichocki requested changes
How about the tooltip animation for the fee tier, were they intentionally left? Additionally, for these tooltips, could we increase the font size and the message content itself?

2024-08-06 23:14 UTC, wojciech-cichocki requested changes
Make both messages consistent:
- The position is **active** and currently **earning a fee** as long as the current price is **within** the position's price range.
- The position is **inactive** and **not earning a fee** as long as the current price is **outside** the position's price range.

2024-08-08 15:44 UTC, wojciech-cichocki approved these changes

2024-08-08 15:44 UTC, merged