Final fixes
invariant-labs/webapp-a0 pull request #271
Opened 2024-08-06 15:11 UTC by p6te

- add tooltips for token link and estimated balance
- add hover highlight for copy market id
- fix tokens animation on swap

2024-08-07 08:16 UTC, zielvna approved these changes

2024-08-08 02:56 UTC, wojciech-cichocki requested changes
IMO, the tooltip for balance should be consistent, because it has been added in only one place. Therefore, it should also be added in other places - the entire app needs to be reviewed to find the remaining locations:
![image](https://github.com/user-attachments/assets/a32f7b7d-b7f4-46ec-955a-63d0111b00bc)

There is none here:
- ![Screenshot from 2024-08-08 04-38-14](https://github.com/user-attachments/assets/26741177-e619-4a07-b489-a98e45ec94a3)
- ![Screenshot from 2024-08-08 04-38-06](https://github.com/user-attachments/assets/e519ec59-73a4-459e-9fa2-2fa236495998)


Additionally, the description should indicate what this balance means, because on "Add position" this value represents the wallet balance of selected token, while on "position details" this balance value represents the token value in the open position.

2024-08-08 14:37 UTC, zielvna commented
![image](https://github.com/user-attachments/assets/57c08440-5ea6-4608-8830-998f0b3dc76d)
there is hover effect on add new position page

2024-08-09 11:38 UTC, wojciech-cichocki commented on src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx
> +                  title='Your Estimated Balance in USD'
```suggestion
                  title='Estimated USD Value of the Selected Tokens in Your Wallet'
```

2024-08-09 11:38 UTC, wojciech-cichocki commented on src/components/Inputs/DepositAmountInput/DepositAmountInput.tsx
> +                  title='Your Estimated Balance in USD'
```suggestion
                  title='Estimated USD Value of the Selected Tokens in Your Wallet'
```

2024-08-09 11:41 UTC, wojciech-cichocki approved these changes

2024-08-09 11:43 UTC, merged