add ability to change network and use custom rpc on each one
invariant-labs/webapp-a0 pull request #288
Opened 2024-08-28 17:10 UTC by zielvna

2024-08-30 07:34 UTC, p6te reviewed
after choosing mainnet network,  select rpc doesn't work. it is settled to custom only with testnet 
![image](https://github.com/user-attachments/assets/5038f521-0799-4e53-abb6-3cc1448e84ad)

2024-08-30 08:08 UTC, p6te commented on src/store/consts/static.ts
> +export const getFaucetTokenList = (network: Network) => {
do we need faucet token list for mainnet as well?

2024-08-30 08:17 UTC, p6te commented
when you choose tokens to swap, then switch network on position list, and go back to swap. tokens changed addresses and can't be readed from URL. maybe we can try to read them properly, because it works, when you stay on swap page. or just clear url to not misunderstand the user. 
[Nagranie ekranu z 30.08.2024 10:12:29.webm](https://github.com/user-attachments/assets/0b7bc48f-c02b-4914-a4f4-de810743270a)

2024-08-30 14:12 UTC, p6te approved these changes

2024-09-02 06:12 UTC, wojciech-cichocki requested changes
We should hide faucet on "Mainnet"
![image](https://github.com/user-attachments/assets/dad35d80-2683-4d25-a304-36195594492c)

2024-09-02 06:14 UTC, wojciech-cichocki requested changes
Probably the mainnet rpc has a different name:
![image](https://github.com/user-attachments/assets/2a64b624-1549-4f0b-b976-b76da1bd19cf)

2024-09-03 06:43 UTC, wojciech-cichocki approved these changes

2024-09-03 06:44 UTC, merged