add refresher to position details
invariant-labs/webapp-a0 pull request #88
Opened 2024-06-11 15:50 UTC by zielvna

2024-06-12 11:54 UTC, p6te commented on src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx
> +  const onRefresh = () => {
here similar question like on the create position. add refresh of balances and token price as well?

2024-06-12 13:48 UTC, p6te approved these changes

2024-06-12 15:46 UTC, wojciech-cichocki requested changes
One of these things is not working correctly:

1. There are no visual loaders in unclaimed fees after triggering refresh
2. Unclaimed fees are not refetched and recalculated

![image](https://github.com/invariant-labs/webapp-a0/assets/43304803/8890ef84-bd2a-4dba-a1d3-2c66e327d271)

2024-06-14 01:46 UTC, wojciech-cichocki approved these changes

2024-06-14 01:47 UTC, merged