enabled refresh button when wallet is disconnected
invariant-labs/webapp-a0 pull request #95
Opened 2024-06-12 13:54 UTC by p6te

![image](https://github.com/invariant-labs/webapp-a0/assets/93533892/ee248d4b-7edc-4940-a033-12135b1482b3)

2024-06-12 14:04 UTC, zielvna approved these changes

2024-06-12 15:15 UTC, wojciech-cichocki requested changes
Things to fix:
1. Disable the refresh button when only one token is selected
2. Skip fetching the price from the API if the wallet is not connected

2024-06-13 04:23 UTC, wojciech-cichocki commented
> Things to fix:
> 
> 1. Disable the refresh button when only one token is selected
> 2. Skip fetching the price from the API if the wallet is not connected

The second one is okay, we won't correct it

2024-06-13 11:37 UTC, wojciech-cichocki approved these changes

2024-06-13 11:39 UTC, merged